### ISSUE TITLE
why OBIS recommends WoRMS LSID to be scientificNameID but not taxonID

### ISSUE THREAD

**Issue by ymgan** [iobis/quality-taskteam#10]
[migrated from Slack]

Yi-Ming Gan
 [Sep 20th at 10:37 AM](https://obishq.slack.com/archives/C013QC3AYH0/p1663663029455149)
Hey, may I know why OBIS recommends WoRMS LSID to be scientificNameID but not taxonID? Because according to Darwin Core definition, I thought the definition that suits WoRMS LSID seems to be closer for taxonID ?
[taxonID](https://dwc.tdwg.org/terms/#dwc:taxonID)
An identifier for the set of taxon information (data associated with the Taxon class). May be a global unique identifier or an identifier specific to the data set.
[scientificNameID](https://dwc.tdwg.org/terms/#dwc:scientificNameID)
An identifier for the nomenclatural (not taxonomic) details of a scientific name.

**Comment by ymgan** [comment]
Hi Yi-MIng, we've been using scientificnameid from the very start, as it is the best/easiest understood by people who need to populate the field (providers & managers). There will always be discussions on the difference between what is a scientific name and what is a taxon, and in which context these should be used, which then also leads into the discussion of 'what is a taxon concept'. What providers give us really is a scientificname. Based on the id that is linked to it, people can find their way to WoRMS, where part of the taxon-information (what is the current name in use) is documented. A scientificnameID is 1-1 linked to the name that is being provided, regardless of whether the taxon is accepted or unaccepted. A whole lot is written and discussed on scientific name concept and taxon concept and can be very interesting discussions in a taxonomic environment, but I would highly recommend to not change the way we are approaching this now.

**Comment by ymgan** [comment]
thank you so much for the explanation!!
I encountered this question when I was looking at the practice from GBIF Norway as they use taxonID for WoRMS LSID field. Their reasoning (based on my understanding) is that WoRMS is not a nomenclator but they also said something about “what is taxon concept” which I do not have much knowledge about - hence I asked this question here. I was further confused by the example on Darwin Core page where GBIF taxonKey (which I look at it as the same type of identifier as AphiaID) is the example of taxonID field, so I am curious why we recommend it to be populated under scientificNameID field.
It is a question out of curiosity as it is also my job as the chair/member of the QC project team to align our practice with TDWG. I am sorry if I come off as questioning many of the previous decisions, because I am curious about the reasons behind it.

**Comment by ymgan** [comment]
Related: 

- https://github.com/tdwg/dwc-qa/issues/172

**Comment by pieterprovoost** [comment]
There is some interesting reading material [here](https://discourse.gbif.org/t/checklist-publishing-on-gbif-some-explanations-on-taxonid-scientificnameid-taxonconceptid-acceptednameusageid-nameaccordingto-gbif-data-blog/3758). Based on this I would argue that the appropriate field is either `scientificNameID` or `taxonConceptID`, but not `taxonID`.

**Comment by ymgan** [comment]
Thank you Pieter! I think you are right, I felt the same after reading the blog.

> The dwc:scientificNameID is meant to identify the name alone and ideally uses an identifier from a nomenclator such as IPNI or ZooBank, but can also be a name identifier specific for the dataset. Our system doesn’t really interpret this field.

I thought it **has to be** from nomenclator but seems like I was wrong.

**Comment by ymgan** [comment]
Opened a ticked on https://github.com/tdwg/dwc-qa/issues/203 for public discussion
