### ISSUE TITLE
recommendation to publish enriched duplicated records

### ISSUE THREAD

**Issue by ymgan** [iobis/quality-taskteam#2]
Opening this issue because I recently have to deal with a dataset which the occurrence records of the specimen are already in GBIF and OBIS. The scientists obtained specimens from multiple museums and conduct isotope measurement and sequenced the specimen and wanted to publish the enriched data. I wonder if OBIS has any recommendation in this?

Suggestions provided by GBIF helpdesk are as follows:

- Contact the museums and ask if it is possible to integrate the measurements and sequences with the original records OR
- Publish the enriched records to GBIF. If the records contain the same core information as the original ones (same catalogue number, collection code, eventDate, etc.), they should be picked up by the [new clustering function](https://www.gbif.org/news/4U1dz8LygQvqIywiRIRpAU/new-data-clustering-feature-aims-to-improve-data-quality-and-reveal-cross-dataset-connections). So in theory, it would be enough to publish the new records with the same core information and extension. However the clustering function is still quite experimental and we don’t include its output in the downloads. So users aren’t notified that duplicates exists. It is recommended to add a note in the `occurrenceRemarks` field reference to the original specimen.

**Comment by pieterprovoost** [comment]
The recommendations would be the same for OBIS with a preference for option 1. We don't do any clustering ourselves but matching related records should be straightforward if `collectionCode` and `catalogNumber` are used consistently. Time and location can be used to complement the identifier fields, although for those I would use intervals to cope with possible differences in precision between different sources.

**Comment by ymgan** [comment]
Sometimes museums such as Senceknberg have Biocase installation that already mobilise the additional data from internal databases into GBIF such as Biocase installation. 

A possible future solution to this issue might be the Digital Extended Specimens work. https://discourse.gbif.org/t/digital-extended-specimens-phase-2/2651
