### ISSUE TITLE
scientificName if taxa is unknown

### ISSUE THREAD

**Issue by ymgan** [iobis/quality-taskteam#29]
Recommendation is to use scientificName == "biota"

There is also a genus called "biota" (https://www.gbif.org/species/7326344). Suggestion to differentiate these is to add taxonRank = "genus" for this one.

**Comment by rubenpp7** [comment]
Adding the higher taxonomy would also help for GBIF not to think that the dataset talk about the genus Biota.
Also adding scientificNameID == "urn:lsid:marinespecies.org:taxname:1" would help
