### ISSUE TITLE
Consider changing the flag for ON_LAND so that it’s not marking species that _should_ be on land according to WoRMS.

### ISSUE THREAD

**Issue by ymgan** [iobis/quality-taskteam#30]
Consider changing the flag for ON_LAND so that it’s not marking species that _should_ be on land according to WoRMS.

- [TDWG DQ tests and assertions](https://docs.google.com/spreadsheets/d/1uwnUtcMSe88AytUt_mSepeLTz54tMvV9llO2pBnObhE) SPECIES_OUTSIDE_EXPERT_RANGE: Geographic coordinates are within/outside the geographic range as defined by 'expert/s' for the taxon
- Fossil of marine species on land

**Comment by 7yl4r** [comment]
If the meaning of `OF_LAND` is going to be changed to "on land when it should not be", then I suggest the name be changed as well.

**Comment by ymgan** [comment]
will be addressed in https://github.com/iobis/obis-qc/issues/26
