### ISSUE TITLE
how to differentiate station depth and actual sampling depth?

### ISSUE THREAD

**Issue by ymgan** [iobis/quality-taskteam#31]
Question from Georgia (MedOBIS) @geo-sar

eg. the sea bottom of station 123 is 50 meters but the samples were taken from a depth of 20 meters (from the water column). How do we map these two values?

**Comment by rubenpp7** [comment]
Like @wardappeltans  said in the call, I would:

sample depth (in the core table):
minimumDepthInMeters = 20
maximumDepthInMeters = 20

station depth (in emof extension table):
measurementType = bottom depth
measurementValue = 50
measurementUnit = metres

**Comment by ymgan** [comment]
How about the use of: 

- **minimumDistanceAboveSurfaceInMeters** 
> The `lesser` distance in a range of distance from a reference surface in the vertical direction, in meters. Use positive values for locations above the surface, negative values for locations below. If depth measures are given, the reference surface is the location given by the depth, otherwise the reference surface is the location given by the elevation.

- **maximumDistanceAboveSurfaceInMeters** 
> The `greater` distance in a range of distance from a reference surface in the vertical direction, in meters. Use positive values for locations above the surface, negative values for locations below. If depth measures are given, the reference surface is the location given by the depth, otherwise the reference surface is the location given by the elevation.

My understanding is:

minimumDepthInMeters: 20
maximumDepthInMeters: 20
minimumDistanceAboveSurfaceInMeters: 0
maximumDistanceAboveSurfaceInMeters: -30 

Edit: as @pieterprovoost pointed out below, what I mentioned above is not right. I did not understand it well.

Even though OBIS has depth values retrieved from GEBCO, the GEBCO's depth value is derived (from model). The actual depth measured would be more accurate, so I think there is a value of adding this to the data. 

Related: 

- https://github.com/gbif/portal-feedback/issues/638

**Comment by pieterprovoost** [comment]
@ymgan Why would we need `minimumDistanceAboveSurfaceInMeters` and `maximumDistanceAboveSurfaceInMeters` here? I understand this is mostly relevant for sediment cores etc? Also, it says that when depth is given this becomes the reference surface, so your numbers would indicate that the samples were collected between 20 and 50 m depth.

**Comment by ymgan** [comment]
oh I think you are right!! It just shows that I didn't understand it. Then what is the difference between:

minimumDepthInMeters: 20
maximumDepthInMeters: 20
minimumDistanceAboveSurfaceInMeters: 0
maximumDistanceAboveSurfaceInMeters: -30

and

minimumDepthInMeters: 20
maximumDepthInMeters: 50

So I guess using eMOF or dynamicProperties is the only way to record the station depth then?

**Comment by ymgan** [comment]
never mind, I am sleeping (haha) I don't know why I did not see the word "range". You are totally right Pieter!

**Comment by pieterprovoost** [comment]
Well, following the definitions you could probably do:

- `minimumDepthInMeters`: 50
- `maximumDepthInMeters`: 50
- `minimumDistanceAboveSurfaceInMeters`: 30
- `maximumDistanceAboveSurfaceInMeters`: 30

But I think that's going to cause a lot of confusion as this is not how we have been using `minimumDepthInMeters` and `maximumDepthInMeters` so far. So yes I would suggest `dynamicProperties` and/or `MeasurementOrFact`.

**Comment by geo-sar** [comment]
Yes!! I think I'll go with what Ruben stated above using this ID: http://vocab.nerc.ac.uk/collection/A05/current/EV_BATHY/
:)
We can consider this issue as resolved!
