### ISSUE TITLE
linking datasets (different taxa) from the same cruise

### ISSUE THREAD

**Issue by ymgan** [iobis/quality-taskteam#32]
Question from Georgia (MedOBIS) @geo-sar

We have a dataset published regarding a specific taxonomic group (polychaetes). Now we want to publish an exact same dataset in terms of sampling event (stations, method, dates, etc) with the only difference being that the taxonomic group changes (crustaceans) and the associated measurements of course (abundance etc). Practically both datasets are from the same cruise, just the different taxnomic groups were analyzed in different times. Is there a way that these two datasets are linked somehow in the IPT (without having to reupload the first one...)?

**Comment by 7yl4r** [comment]
The common way of doing this is to use Event-core, where the cruise is documented as an Event and the occurrences then reference the ParentEventID of that event.

**Comment by rubenpp7** [comment]
I can think of several options (none of them is a standard protocol):

- Merge the datasets in Event Core. (Something I would probably do if the data creators are ok with it, since the 2 datasets seem to be extracted from the same samples)

- Linking the datasets without merging them. (If the datasets must not be merged for whatever reason)
       - In the data. Use same eventIDs in both datasets
       - In the data. Use dataset identifiers within the other dataset. Example: eventID of dataset 2 contains the DOI of dataset 1
       - In the metadata. Add explicit references about the other dataset in the Abstract for example. Use the same format for Title and other metadata fields

**Comment by ymgan** [comment]
Thank you @7yl4r and @rubenpp7 !! I like option 2 suggested by @rubenpp7 

Option 1 

- if the dataset is funded by different project and carried out by different people, I think publishing it as a separate dataset allows the people to be properly credited. 


Option 2 

- Can the crustaceans dataset then be published just as Occurrence core with eventID referencing the eventID in the polychaetes dataset similar to the [sibling datasets from Andre](https://discourse.gbif.org/t/sibling-datasets-to-overcome-dwcarchive-star-schema-limitation-2/3401)? Or perhaps that is not a great idea here because Georgia will then have to duplicate all the Event core fields into Occurrence core? If something changes, she will have to update both Event core from polychaetes dataset and all duplicated event related fields in occurrence core for crustaceans dataset ... 

- If there are eMOF records for Events in the polychaetes dataset, does that mean that Georgia also need to duplicate that in the crustaceans dataset? 

Would be great to have your input on this too @pieterprovoost 

@ManonGros - can we check with you what GBIF's recommendation is please? Georgia's datasets also go to GBIF and this task team aims to align our practices with GBIF and TDWG. We hope to come up with solutions that work well for both GBIF and OBIS system~

Thanks a lot all! I will @ Georgia once I found her GitHub handle :)

**Comment by ymgan** [comment]
@geo-sar

**Comment by pieterprovoost** [comment]
If the contacts and other metadata are the same between both datasets then yes, I would consider merging them into one.

If not then in theory you could publish three datasets: one with the shared event data, and two occurrence datasets. However, as we are currently not resolving event identifiers between datasets, for us it would be best if both datasets are published as event core datasets with all the necessary details. But that's just the OBIS perspective. In this case make sure to use persistent globally unique event identifiers.

Additionally, if you are publishing multiple datasets, link them in the metadata using External links and Project metadata.

**Comment by ManonGros** [comment]
At GBIF, we think think Pieter's suggestion makes a lot of sense: two datasets with event core and reference to each other in the metadata.

**Comment by geo-sar** [comment]
The data provider IS the same and he actually preferes the two datasets to be merged into one, even have the same url and doi if possible. Is this feasible?
The datasetName should also change since now it's "Polychaetes from major ports in Greece in 2020-2021". 
Since the provider is ok, I wouldn't have a problem deleting the already uploaded dataset (polychaetes) and reupload the merged one, but is this considered ok by OBIS anf GBIF as a practice?
If not, I am open to hear how the merging would be applied:)
Thank you all for your time and answers!

**Comment by pieterprovoost** [comment]
@geo-sar No need to remove the existing dataset, you just need to update its data files. In IPT, go to Source Data, remove the existing data files, and reupload. You will also have to do the mappings again in the Darwin Core Mappings section. The title can be updated in the Metadata section.

**Comment by geo-sar** [comment]
Awsome then! :) thanks a lot Peter:)

**Comment by ymgan** [comment]
@geo-sar I presume that the issue is resolved so I gonna close this. Please reopen the issue if it is not. Thanks a lot!
