### ISSUE TITLE
publishing dataset with museum specimen with COI sequences in BOLD

### ISSUE THREAD

**Issue by ymgan** [iobis/quality-taskteam#36]
I have a dataset where researchers sequenced COI of a museum specimen (which has persistent identifier for occurrenceID) and have all the sequences and its metadata in [BOLD](https://www.boldsystems.org/). I wonder if anyone else have the same kind of datasets? Do you use DNA-derived data extension for this?

**Comment by ymgan** [comment]
@timrobertson100 pointed some examples of museum specimen data published with DNA derived data extension https://www.gbif.org/occurrence/search?basis_of_record=PRESERVED_SPECIMEN&taxon_key=54&advanced=1&occurrence_status=present&dwca_extension=http:~2F~2Frs.gbif.org~2Fterms~2F1.0~2FDNADerivedData

**Comment by pieterprovoost** [comment]
@ymgan We also have some specimens here:

- Molecular Sequences of Deepsea Caridean Shrimp based on 16S and COI from Southern coast of India during 2013-2017
  - Dataset: https://obis.org/dataset/f61ec56a-9295-4224-9f70-67a058837ed5
  - Occurrences: https://api.obis.org/occurrence?datasetid=f61ec56a-9295-4224-9f70-67a058837ed5&dna=true
- DNA barcoding of the Anomuran crabs of Indian EEZ using COI and 16S rRNA genes
  - Dataset: https://obis.org/dataset/d7bf65ae-d272-4ee1-a296-d4f33bca827e
  - Occurrences: https://api.obis.org/occurrence?datasetid=d7bf65ae-d272-4ee1-a296-d4f33bca827e&dna=true

The nice thing about publishing the sequences to OBIS and GBIF with DNADerivedData is that we can build tools like this prototype: https://sequence.obis.org/ Try with the sequence below for example:

```
GACAACTAGTTGGACTGGCCTGCCACTGAAGTAATTTAAAGGGCCGCGGTAATTTGACCGTGCGAAGGTAGCATAATCAATAGTCTCTTAATTGGAGGCTGGAATGAATGGTCGGACAAGGAGTGGACTGTCTTTTTCTTATCTTATGAAGTTTACTTTTAAGTGAAAAGGCTTAAATATACTTGGGGGACGATAAGACCCTATAAAACTTTACAGTATAGTTTATATTTTATGAAATAAAATTTAATGTTGGTTATGAGTTATCTGTTATGTTGGGGTGACAAAGATATAATTAGTAACTGTCAGACAATGGTAATAATAATAATTAGATTATTTATTAGAGATTATAAGATTAAGTTACTTTAGGGATAACAGCGTAATTTTCTTTGAGAGTTCTTATCGACAAGAATAGTTGCGACCTCGATGTTGAATTAAGATTTCTTTTAAATGTAGCAGTTTAATCAGTAGGTCTGTTCGACCTTTAAAATCTTACGTGATCTGAGTTCAGACCGGACTTTTTATATGAACCAATTTAATTAGTAAGGTCTGCTTGACCTTTTAAAATCTTACGTGATCTGAGTTCAGACCGGACGT
```

All PacMAN specimens will be published using DNADerivedData.

**Comment by ymgan** [comment]
Thank you so much Pieter!! That is really nice!

Out of curiosity, does BOLD push everything to GBIF? (https://www.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c) If so, it means the occurrence that I am about to publish is probably already in there. But the data provider would need this for a data paper. Is there a way that we could link the data together? @timrobertson100

**Comment by timrobertson100** [comment]
> Is there a way that we could link the data together? @timrobertson100

At GBIF we periodically run [clustering](https://data-blog.gbif.org/post/clustering-occurrences/) which will link both records provided sufficient criteria are met. Paying attention to catalogNumbers and other IDs, location and date information are important to improve the linking.

We crawl BOLD through their APIs and generate a DwC-A for them.

Both of these are batch processes, so eventually things become consistent but it doesn't happen in real time as data are indexed.

I hope this helps.

**Comment by ymgan** [comment]
Thank you so much Tim! That's absolutely helpful!!

**Comment by ymgan** [comment]
Hey @pieterprovoost, 

I just wanted to make sure that I get right. When you said

> The nice thing about publishing the sequences to OBIS and GBIF with DNADerivedData is that we can build tools like this prototype: https://sequence.obis.org/ 

Is there a particular field where you get the sequences? Is it the `DNA_sequence` field? or do you get it from API using certain identifiers? Then I can encourage our data providers to fill in the field that helps you build the tool :)

**Comment by timrobertson100** [comment]
Hi @ymgan - the [README](https://github.com/iobis/sequence-search) suggests it's using the `DNA_sequence` field as you suspect. It looks like it generates a lookup table from the core index for that app to work against.

> Then I can encourage our data providers to fill in the field that helps you build the tool :)

Please do! I anticipate similar tools on GBIF in the not-too-distant future as well.

Thank you

**Comment by pieterprovoost** [comment]
Yes that's correct, we build a reference database from the sequences in `DNA_sequence` to query against.
